project_name: xoul

wandb:
  project: xoul

training:
  model_name: sophosympatheia/Midnight-Miqu-70B-v1.0
  batch_size: 2
  num_epochs: 5
  learning_rate: 5e-5
  grad_accumulation_steps: 2
  checkpointing_steps: 500
  save_path: ./models
  ckpt_path: ""
  max_length: 400  # Tokenizer 的最大长度
  num_warmup_steps: 0
  train_data_path: /ephemeral/homework/data/threads/*.txt  # 训练数据路径

lora:
  r: 4
  lora_alpha: 32
  lora_dropout: 0.1
  target_modules:
    - q_proj
    - o_proj
    - k_proj
    - v_proj
    - gate_proj
    - up_proj
    - down_proj
